/**
 * ================================================================
 * Automated Script Enterprise Automation Framework
 * ------------------------------------------------
 * Module  : Self Healing
 * File    : HealingResult.js
 * Purpose : Represents final locator healing execution result
 *  Purpose of this class:

Immutable result object returned by SelfHealingEngine
Standard communication between:
SelfHealingEngine
BaseElement
LocatorRepository
Allure attachments
Avoid passing raw objects everywhere
Capture complete healing decision history
 * Author  : Automated Script
 * ================================================================
 */


/**
 * Represents result generated by SelfHealingEngine.
 *
 * This object carries:
 *  - Original failed locator
 *  - Final resolved locator
 *  - Healing status
 *  - Healing strategy
 *  - Confidence score
 *  - Additional message/details
 *
 * @class HealingResult
 */
export class HealingResult {


    /**
     * Creates HealingResult instance.
     *
     * @param {Object} options
     * @param {boolean} options.healed
     * @param {string} options.originalLocator
     * @param {string} options.resolvedLocator
     * @param {string} options.strategy
     * @param {number} options.confidence
     * @param {string} options.message
     */
    constructor({

        healed = false,

        originalLocator = null,

        resolvedLocator = null,

        strategy = "ORIGINAL",

        confidence = 1,

        message = ""

    } = {}) {


        /**
         * Whether locator was healed
         */
        this.healed = healed;


        /**
         * Original locator passed from Page Object
         */
        this.originalLocator = originalLocator;


        /**
         * Locator finally used by framework
         */
        this.resolvedLocator = resolvedLocator;


        /**
         * Healing strategy applied
         *
         * Possible:
         * ORIGINAL
         * PREVIOUS_SUCCESSFUL
         * ATTRIBUTE_MATCH
         * SIMILARITY_MATCH
         * XPATH_FALLBACK
         * FAILED
         */
        this.strategy = strategy;


        /**
         * Confidence percentage
         *
         * 0 - 1
         */
        this.confidence = confidence;


        /**
         * Additional information
         */
        this.message = message;


        /**
         * Timestamp for reporting/debugging
         */
        this.timestamp =
            new Date().toISOString();


        Object.freeze(this);
    }



    /**
     * Returns whether healing happened successfully.
     *
     * @returns {boolean}
     */
    isHealed(){

        return this.healed;
    }



    /**
     * Returns resolved locator.
     *
     * @returns {string}
     */
    getLocator(){

        return this.resolvedLocator;
    }



    /**
     * Convert result into JSON format.
     *
     * Used by:
     *  - Allure attachment
     *  - Logging
     *
     * @returns {Object}
     */
    toJSON(){

        return {

            healed:
                this.healed,

            originalLocator:
                this.originalLocator,

            resolvedLocator:
                this.resolvedLocator,

            strategy:
                this.strategy,

            confidence:
                this.confidence,

            message:
                this.message,

            timestamp:
                this.timestamp
        };
    }



    /**
     * Successful original locator result.
     *
     * @param {string} locator
     * @returns {HealingResult}
     */
    static original(locator){

        return new HealingResult({

            healed:false,

            originalLocator:locator,

            resolvedLocator:locator,

            strategy:"ORIGINAL",

            confidence:1,

            message:
                "Original locator resolved successfully"

        });
    }



    /**
     * Successful healing result.
     *
     * @param {Object} data
     * @returns {HealingResult}
     */
    static success(data){

        return new HealingResult({

            healed:true,

            ...data

        });
    }



    /**
     * Failed healing result.
     *
     * @param {string} locator
     * @param {string} message
     *
     * @returns {HealingResult}
     */
    static failure(locator,message){

        return new HealingResult({

            healed:false,

            originalLocator:locator,

            resolvedLocator:null,

            strategy:"FAILED",

            confidence:0,

            message

        });
    }

}